(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sb=()=>window.bm7Supabase, me=()=>window.BM7Live?.user;
const toast=t=>window.showToast?window.showToast(t):console.log(t);
function css(){if(document.getElementById('bm7AvatarCSS'))return;const s=document.createElement('style');s.id='bm7AvatarCSS';s.textContent=`.bm7-avatar-picker{display:flex;align-items:center;gap:14px;margin:14px 0;padding:14px;border:1px solid #30363d;border-radius:16px;background:#101419}.bm7-avatar-preview{width:72px;height:72px;border-radius:50%;background:#20252b center/cover no-repeat;display:grid;place-items:center;font-size:30px;overflow:hidden;flex:0 0 auto}.bm7-avatar-actions{display:flex;gap:8px;flex-wrap:wrap}.bm7-avatar-actions button{border:0;border-radius:10px;padding:9px 13px;cursor:pointer;font-weight:800}.bm7-avatar-main{background:#ffc400;color:#111}.bm7-avatar-remove{background:#252b32;color:#eee}.bm7-user-avatar-img{width:100%;height:100%;object-fit:cover;border-radius:50%;display:block}`;document.head.appendChild(s)}
function setAvatar(el,url){if(!el)return;if(url){el.style.backgroundImage=`url("${url}")`;el.textContent='';if(el.querySelector('img'))el.querySelector('img').src=url}else{el.style.backgroundImage='';el.textContent='🦇'}}
async function getProfile(){const S=sb(),u=me();if(!S||!u)return null;const r=await S.from('profiles').select('avatar_url,username,display_name').eq('id',u.id).maybeSingle();return r.data||null}
async function refreshMine(){const p=await getProfile();const url=p?.avatar_url||localStorage.getItem('bm7_avatar')||'';if(url)localStorage.setItem('bm7_avatar',url);document.querySelectorAll('[data-bm7-my-avatar]').forEach(e=>setAvatar(e,url));const prev=document.getElementById('bm7AvatarPreview');if(prev)setAvatar(prev,url);}
async function chooseAvatar(){const input=document.getElementById('bm7AvatarInput');if(input)input.click()}
async function uploadAvatar(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;const u=me(),S=sb();if(!u||!S){toast('سجّل الدخول أولاً');return}if(!f.type.startsWith('image/')){toast('اختر صورة فقط');return}if(f.size>5*1024*1024){toast('حجم الافتار يجب أن يكون أقل من 5MB');return}toast('جاري رفع الافتار…');const ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`avatars/${u.id}-${Date.now()}.${ext}`;const up=await S.storage.from('bm7-media').upload(path,f,{contentType:f.type,upsert:false});if(up.error){toast('تعذر رفع الافتار: '+up.error.message);return}const url=S.storage.from('bm7-media').getPublicUrl(path).data.publicUrl;const r=await S.from('profiles').update({avatar_url:url}).eq('id',u.id);if(r.error){toast('تعذر حفظ الافتار: '+r.error.message);return}localStorage.setItem('bm7_avatar',url);refreshMine();toast('✨ تم تحديث افتارك');}
async function removeAvatar(){const S=sb(),u=me();if(!S||!u){localStorage.removeItem('bm7_avatar');refreshMine();return}const r=await S.from('profiles').update({avatar_url:null}).eq('id',u.id);if(r.error){toast('تعذر إزالة الافتار');return}localStorage.removeItem('bm7_avatar');refreshMine();toast('تمت إزالة الافتار');}
function inject(){css();if(document.getElementById('bm7AvatarPicker'))return;let host=document.getElementById('profileSection')||document.getElementById('section-profile')||document.querySelector('[id*=profile]');if(!host){setTimeout(inject,1200);return}const box=document.createElement('div');box.id='bm7AvatarPicker';box.className='bm7-avatar-picker';box.innerHTML=`<div class="bm7-avatar-preview" id="bm7AvatarPreview">🦇</div><div><b>صورتك الشخصية</b><div class="muted" style="margin:4px 0 9px">اختَر أي صورة لتكون افتارك في BM7</div><div class="bm7-avatar-actions"><button class="bm7-avatar-main" id="bm7PickAvatar">📷 اختيار افتار</button><button class="bm7-avatar-remove" id="bm7RemoveAvatar">حذف</button></div></div><input id="bm7AvatarInput" type="file" accept="image/*" style="display:none">`;host.insertBefore(box,host.firstChild);document.getElementById('bm7PickAvatar').onclick=chooseAvatar;document.getElementById('bm7RemoveAvatar').onclick=removeAvatar;document.getElementById('bm7AvatarInput').onchange=uploadAvatar;refreshMine()}
async function hydrateOtherAvatars(){const S=sb();if(!S)return;const rows=[...document.querySelectorAll('#bm7Contacts .bm7-contact')];const ids=[];rows.forEach(r=>{const m=(r.getAttribute('onclick')||'').match(/bm7RealtimeChat\(\s*['\"][^'\"]+['\"]\s*,\s*['\"]([^'\"]+)/);if(m)ids.push(m[1])});if(!ids.length)return;const r=await S.from('profiles').select('id,avatar_url').in('id',ids);(r.data||[]).forEach(p=>{document.querySelectorAll(`[data-bm7-user-avatar="${CSS.escape(p.id)}"]`).forEach(e=>setAvatar(e,p.avatar_url))})}
function watch(){new MutationObserver(()=>{document.querySelectorAll('.bm7-contact').forEach(r=>{const m=(r.getAttribute('onclick')||'').match(/bm7RealtimeChat\(\s*['\"][^'\"]+['\"]\s*,\s*['\"]([^'\"]+)/);if(m){const a=r.querySelector('.bm7-avatar');if(a){a.dataset.bm7UserAvatar=m[1];}}});}).observe(document.body,{childList:true,subtree:true});}
window.bm7PickAvatar=chooseAvatar;window.bm7RefreshAvatar=refreshMine;
setTimeout(()=>{inject();watch();hydrateOtherAvatars()},1200);setInterval(()=>{inject();hydrateOtherAvatars();refreshMine()},5000);
})();