(()=>{
  const KEY='bm7_chats_v1';
  const state={peer:null,peerName:'',messages:[],channel:null,remoteReady:false};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const getStore=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const saveStore=x=>localStorage.setItem(KEY,JSON.stringify(x));
  const uid=()=>window.BM7Live?.user?.id||null;
  const avatar=()=>localStorage.getItem('bm7_avatar')||'';
  const showToast=t=>window.showToast?window.showToast(t):console.log(t);
  function inject(){
    if(document.getElementById('bm7ChatOverlay'))return;
    const style=document.createElement('style');style.id='bm7ChatStyle';style.textContent=`
#bm7ChatOverlay{position:fixed;inset:0;z-index:999990;background:#090c10;color:#eee;display:none;font-family:Arial,sans-serif;direction:rtl}
#bm7ChatOverlay.open{display:grid;grid-template-columns:minmax(300px,390px) 1fr}
.bm7-chat-side{border-left:1px solid #242a31;background:#0b0e12;display:flex;flex-direction:column;min-width:0}
.bm7-chat-side-head{height:76px;border-bottom:1px solid #242a31;display:flex;align-items:center;justify-content:space-between;padding:0 18px;box-sizing:border-box}
.bm7-chat-side-head h2{margin:0;font-size:20px}.bm7-chat-icon{border:0;background:transparent;color:#ddd;font-size:21px;cursor:pointer;padding:7px;border-radius:9px}.bm7-chat-icon:hover{background:#171c22}
.bm7-chat-search{margin:14px 14px 8px;background:#1a1f25;border:0;border-radius:18px;padding:11px 15px;color:#fff;outline:none;font-size:14px}
#bm7ChatList{overflow:auto;flex:1;padding:4px 8px 20px}.bm7-chat-person{display:flex;gap:11px;align-items:center;padding:12px 10px;border-radius:13px;cursor:pointer}.bm7-chat-person:hover,.bm7-chat-person.sel{background:#20252b}.bm7-chat-person .ava,.bm7-chat-header .ava{width:48px;height:48px;border-radius:50%;background:#20252b center/cover no-repeat;display:grid;place-items:center;flex:0 0 auto;font-size:20px}.bm7-chat-person .dot{width:11px;height:11px;background:#27d45a;border:2px solid #0b0e12;border-radius:50%;margin-right:-17px;margin-top:31px}.bm7-chat-person .meta{min-width:0;flex:1}.bm7-chat-person b{display:block;font-size:14px}.bm7-chat-person .preview{color:#9098a1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:12px;margin-top:4px}
.bm7-chat-main{min-width:0;display:flex;flex-direction:column;background:#080b0f}.bm7-chat-header{height:76px;border-bottom:1px solid #242a31;display:flex;align-items:center;padding:0 18px;gap:11px}.bm7-chat-header .head-info{flex:1;min-width:0}.bm7-chat-header .head-info b{display:block;font-size:15px}.bm7-chat-header .head-info span{font-size:11px;color:#8f98a1}.bm7-chat-actions{display:flex;gap:3px}.bm7-chat-messages{flex:1;overflow:auto;padding:28px 7%;display:flex;flex-direction:column;gap:8px;scroll-behavior:smooth}.bm7-chat-empty{margin:auto;text-align:center;color:#7e8790}.bm7-chat-empty strong{display:block;color:#ddd;font-size:17px;margin-bottom:6px}.bm7-bubble{max-width:min(520px,72%);padding:10px 13px;border-radius:18px;font-size:14px;line-height:1.55;word-break:break-word;position:relative}.bm7-bubble.me{align-self:flex-start;background:#ffc400;color:#111;border-bottom-left-radius:5px}.bm7-bubble.them{align-self:flex-end;background:#20252b;color:#eee;border-bottom-right-radius:5px}.bm7-bubble .time{display:block;font-size:9px;opacity:.55;margin-top:4px}.bm7-image{max-width:260px;max-height:340px;border-radius:14px;display:block;object-fit:cover}
.bm7-chat-compose{padding:12px 18px 17px;border-top:1px solid #242a31;background:#0a0d11}.bm7-chat-compose-inner{display:flex;align-items:center;gap:7px;border:1px solid #30363d;border-radius:24px;background:#11151a;padding:4px 6px}.bm7-chat-compose input{flex:1;border:0;outline:0;background:transparent;color:#fff;padding:10px 8px;font-size:14px;direction:rtl}.bm7-chat-compose button{border:0;background:transparent;color:#ddd;font-size:20px;cursor:pointer;border-radius:50%;width:38px;height:38px}.bm7-chat-compose button:hover{background:#20252b}.bm7-send{background:#ffc400!important;color:#111!important;font-size:16px!important;font-weight:900}.bm7-chat-file{display:none}.bm7-chat-back{display:none}
@media(max-width:760px){#bm7ChatOverlay.open{grid-template-columns:1fr}.bm7-chat-side{display:none}.bm7-chat-side.mobile-show{display:flex}.bm7-chat-main.mobile-hide{display:none}.bm7-chat-back{display:block}.bm7-chat-messages{padding:20px 14px}.bm7-bubble{max-width:80%}}
`;
    document.head.appendChild(style);
    const o=document.createElement('div');o.id='bm7ChatOverlay';o.innerHTML=`
      <aside class="bm7-chat-side" id="bm7ChatSide"><div class="bm7-chat-side-head"><h2>الرسائل</h2><div><button class="bm7-chat-icon" id="bm7NewChat" title="رسالة جديدة">✎</button><button class="bm7-chat-icon" id="bm7CloseChat" title="إغلاق">×</button></div></div><input class="bm7-chat-search" id="bm7ChatSearch" placeholder="بحث في الرسائل..."/><div id="bm7ChatList"></div></aside>
      <main class="bm7-chat-main" id="bm7ChatMain"><header class="bm7-chat-header"><button class="bm7-chat-icon bm7-chat-back" id="bm7ChatBack">→</button><div class="ava" id="bm7ChatAvatar">🦇</div><div class="head-info"><b id="bm7ChatName">اختر محادثة</b><span id="bm7ChatStatus">—</span></div><div class="bm7-chat-actions"><button class="bm7-chat-icon" id="bm7ChatInfo" title="معلومات الحساب">ⓘ</button><button class="bm7-chat-icon" id="bm7ChatVideo" title="مكالمة فيديو">▣</button><button class="bm7-chat-icon" id="bm7ChatCall" title="مكالمة صوتية">☎</button></div></header><div class="bm7-chat-messages" id="bm7ChatMessages"><div class="bm7-chat-empty"><strong>💬 رسائلك</strong><span>اختر شخصًا من القائمة لبدء محادثة</span></div></div><div class="bm7-chat-compose"><div class="bm7-chat-compose-inner"><button id="bm7Emoji" title="إيموجي">☺</button><label for="bm7ChatFile" class="bm7-chat-icon" title="صورة">▧</label><input id="bm7ChatFile" class="bm7-chat-file" type="file" accept="image/*"/><input id="bm7ChatInput" placeholder="مراسلة..." autocomplete="off"/><button class="bm7-send" id="bm7ChatSend">➤</button></div></div></main>`;
    document.body.appendChild(o);
    document.getElementById('bm7CloseChat').onclick=close;
    document.getElementById('bm7ChatBack').onclick=()=>{document.getElementById('bm7ChatSide').classList.add('mobile-show');document.getElementById('bm7ChatMain').classList.add('mobile-hide')};
    document.getElementById('bm7ChatSend').onclick=send;
    document.getElementById('bm7ChatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
    document.getElementById('bm7Emoji').onclick=()=>{const i=document.getElementById('bm7ChatInput');i.value+=' 😊';i.focus()};
    document.getElementById('bm7ChatFile').onchange=sendImage;
    document.getElementById('bm7ChatSearch').oninput=e=>renderList(e.target.value);
    document.getElementById('bm7NewChat').onclick=newChat;
    document.getElementById('bm7ChatCall').onclick=()=>{if(state.peer)window.startCall?.(state.peerName,'audio')};
    document.getElementById('bm7ChatVideo').onclick=()=>{if(state.peer)window.startCall?.(state.peerName,'video')};
    document.getElementById('bm7ChatInfo').onclick=()=>{if(state.peer)showToast('فتح حساب @'+state.peerName);};
  }
  async function open(name,id){inject();state.peer=id;state.peerName=name||'مستخدم';document.getElementById('bm7ChatOverlay').classList.add('open');document.getElementById('bm7ChatSide').classList.remove('mobile-show');document.getElementById('bm7ChatMain').classList.remove('mobile-hide');setHeader();await load();subscribe();renderList();}
  function close(){const o=document.getElementById('bm7ChatOverlay');if(o)o.classList.remove('open');if(state.channel&&window.bm7Supabase){try{window.bm7Supabase.removeChannel(state.channel)}catch{}}state.channel=null}
  function setHeader(){const a=document.getElementById('bm7ChatAvatar');const src=avatar();a.style.backgroundImage=src?`url(${src})`:'';a.textContent=src?'':'🦇';document.getElementById('bm7ChatName').textContent='@'+state.peerName;document.getElementById('bm7ChatStatus').textContent='محادثة خاصة';}
  function localMessages(){const s=getStore(),k=[uid()||'guest',state.peer].sort().join(':');return s[k]||[]}
  async function load(){state.messages=localMessages();const sb=window.bm7Supabase;if(sb&&uid()&&state.peer){try{const r=await sb.from('messages').select('id,sender_id,receiver_id,body,media_url,created_at').or(`and(sender_id.eq.${uid()},receiver_id.eq.${state.peer}),and(sender_id.eq.${state.peer},receiver_id.eq.${uid()})`).order('created_at',{ascending:true});if(!r.error&&r.data){state.remoteReady=true;state.messages=r.data.map(x=>({id:x.id,me:x.sender_id===uid(),body:x.body||'',media:x.media_url||'',created_at:x.created_at}));}}catch{state.remoteReady=false}}renderMessages()}
  function subscribe(){const sb=window.bm7Supabase;if(!sb||!uid()||!state.peer)return;if(state.channel)try{sb.removeChannel(state.channel)}catch{};state.channel=sb.channel('bm7-chat-'+[uid(),state.peer].sort().join('-')).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`receiver_id=eq.${uid()}`},p=>{const x=p.new;if(x.sender_id===state.peer){state.messages.push({id:x.id,me:false,body:x.body||'',media:x.media_url||'',created_at:x.created_at});renderMessages()}}).subscribe();}
  function renderList(filter=''){const box=document.getElementById('bm7ChatList');if(!box)return;const contacts=[...document.querySelectorAll('#bm7Contacts .bm7-contact')].map(x=>({id:x.getAttribute('onclick')?.match(/,'([^']+)'\)/)?.[1],name:(x.querySelector('b')?.textContent||'').replace(/^@/,''),status:x.querySelector('.bm7-status-text')?.textContent||'غير متصل'})).filter(x=>x.id);let list=contacts.filter(x=>(x.name+' '+x.status).toLowerCase().includes(filter.toLowerCase()));if(!list.length){box.innerHTML='<div style="padding:30px;text-align:center;color:#777">لا توجد محادثات بعد</div>';return}box.innerHTML=list.map(x=>{const lm=localLast(x.id);const sel=state.peer===x.id?' sel':'';return `<div class="bm7-chat-person${sel}" data-id="${esc(x.id)}"><div class="ava">🦇</div><div class="dot"></div><div class="meta"><b>@${esc(x.name)}</b><div class="preview">${esc(lm?.body||x.status||'ابدأ محادثة جديدة')}</div></div></div>`}).join('');box.querySelectorAll('.bm7-chat-person').forEach(el=>el.onclick=()=>{const x=list.find(a=>a.id===el.dataset.id);if(x)open(x.name,x.id)});}
  function localLast(id){const s=getStore(),k=[uid()||'guest',id].sort().join(':');const a=s[k]||[];return a[a.length-1]}
  function renderMessages(){const box=document.getElementById('bm7ChatMessages');if(!box)return;if(!state.messages.length){box.innerHTML='<div class="bm7-chat-empty"><strong>ابدأ المحادثة 👋</strong><span>أرسل أول رسالة إلى @'+esc(state.peerName)+'</span></div>';return}box.innerHTML=state.messages.map(m=>`<div class="bm7-bubble ${m.me?'me':'them'}">${m.media?`<img class="bm7-image" src="${esc(m.media)}" alt="صورة"/>`:''}${m.body?esc(m.body):''}<span class="time">${m.created_at?new Date(m.created_at).toLocaleTimeString('ar-SA',{hour:'numeric',minute:'2-digit'}):''}</span></div>`).join('');box.scrollTop=box.scrollHeight;}
  async function send(){const i=document.getElementById('bm7ChatInput'),body=i.value.trim();if(!body||!state.peer)return;i.value='';const now=new Date().toISOString();const msg={me:true,body,media:'',created_at:now};state.messages.push(msg);saveLocal();renderMessages();const sb=window.bm7Supabase;if(sb&&uid()){try{const r=await sb.from('messages').insert({sender_id:uid(),receiver_id:state.peer,body}).select().single();if(!r.error&&r.data){msg.id=r.data.id;state.remoteReady=true}}catch{}}renderList();}
  async function sendImage(e){const f=e.target.files?.[0];e.target.value='';if(!f||!state.peer)return;if(f.size>6*1024*1024){showToast('الصورة يجب أن تكون أقل من 6MB');return}const rd=new FileReader();rd.onload=async()=>{const msg={me:true,body:'',media:String(rd.result),created_at:new Date().toISOString()};state.messages.push(msg);saveLocal();renderMessages();showToast('تم إرسال الصورة ✨');};rd.readAsDataURL(f)}
  function saveLocal(){const s=getStore(),k=[uid()||'guest',state.peer].sort().join(':');s[k]=state.messages.slice(-100);saveStore(s)}
  function newChat(){const n=prompt('اكتب اسم المستخدم لبدء محادثة');if(!n)return;const row=[...document.querySelectorAll('#bm7Contacts .bm7-contact')].find(x=>(x.querySelector('b')?.textContent||'').replace('@','').trim().toLowerCase()===n.replace('@','').trim().toLowerCase());if(row){row.click()}else showToast('لم نجد هذا المستخدم ضمن الحسابات المتاحة');}
  window.openBM7Chat=open;
  window.bm7Message=(name)=>{const row=[...document.querySelectorAll('#bm7Contacts .bm7-contact')].find(x=>(x.querySelector('b')?.textContent||'').includes(name));const id=row?.getAttribute('onclick')?.match(/,'([^']+)'\)/)?.[1];if(id)open(name,id);else showToast('افتح الرسائل ثم اختر المستخدم لبدء المحادثة');};
  window.bm7CloseChat=close;
  setTimeout(inject,500);
})();