const BM7KEY='bm7_stats_v2';
let bm7Stats=JSON.parse(localStorage.getItem(BM7KEY)||'null')||{xp:0,wins:0,streak:1,lastDay:new Date().toDateString(),missions:{}};
function saveStats(){localStorage.setItem(BM7KEY,JSON.stringify(bm7Stats));updateStatsUI()}
function level(){return Math.floor(bm7Stats.xp/100)+1}
function addXP(n,reason){bm7Stats.xp+=n; if(reason) showToast('+'+n+' XP — '+reason+' 🏆'); saveStats()}
function updateStatsUI(){const lv=level(),cur=bm7Stats.xp%100; ['xpBig','miniXP','boardXP'].forEach(id=>{let e=document.getElementById(id);if(e)e.textContent=id==='boardXP'?bm7Stats.xp+' XP':bm7Stats.xp}); ['levelBig','miniLevel'].forEach(id=>{let e=document.getElementById(id);if(e)e.textContent=lv}); let e=document.getElementById('winsBig');if(e)e.textContent=bm7Stats.wins;e=document.getElementById('streakBig');if(e)e.textContent=bm7Stats.streak;e=document.getElementById('xpBar');if(e)e.style.width=cur+'%';e=document.getElementById('xpText');if(e)e.textContent=cur+' / 100 XP';}
function claimMission(id){const today=new Date().toDateString();bm7Stats.missions[today]=bm7Stats.missions[today]||{};if(bm7Stats.missions[today][id]){showToast('المهمة مكتملة اليوم ✅');return}const vals={post:25,game:15,login:20,community:30};bm7Stats.missions[today][id]=true;addXP(vals[id],'مهمة اليوم');}
function startReaction(){const b=document.getElementById('reactionBtn'),m=document.getElementById('reactionMsg');b.disabled=true;m.textContent='انتظر...';const wait=800+Math.random()*2600;setTimeout(()=>{let t=performance.now();b.disabled=false;b.textContent='اضغط الآن!';b.onclick=()=>{const ms=Math.round(performance.now()-t);b.onclick=startReaction;b.textContent='إعادة';m.textContent='سرعتك: '+ms+'ms';let gain=ms<350?40:ms<650?25:15;bm7Stats.wins++;addXP(gain,'اختبار السرعة');}},wait)}
const quizAnswers=['باتمان','فلاش','سوبرمان'];let qIndex=0;function quizAnswer(btn,ans){const correct=ans===quizAnswers[qIndex%quizAnswers.length];document.querySelectorAll('#section-games .choice').forEach(x=>x.disabled=true);document.getElementById('quizMsg').textContent=correct?'إجابة صحيحة! +25 XP':'ليست الإجابة الصحيحة.';if(correct){bm7Stats.wins++;addXP(25,'سؤال البطل')}setTimeout(()=>{qIndex++;document.getElementById('quizQ').textContent=['من هو حارس مدينة غوثام؟','من الأسرع بين هؤلاء؟','من يرتبط بكوكب كريبتون؟'][qIndex%3];document.querySelectorAll('#section-games .choice').forEach(x=>x.disabled=false)},700)}
let batEnd=0,batScore=0;function batGameStart(){batScore=0;batEnd=Date.now()+10000;document.getElementById('batArea').style.display='block';document.getElementById('batScore').textContent=0;showToast('بدأت الجولة! لديك 10 ثوانٍ');setTimeout(()=>{if(Date.now()>=batEnd){document.getElementById('batArea').style.display='none';let gain=Math.min(60,10+batScore*3);bm7Stats.wins++;addXP(gain,'ضربة الوطواط: '+batScore+' ضربة')}},10100)}function batHit(){if(Date.now()>batEnd)return;batScore++;document.getElementById('batScore').textContent=batScore}
function rollDice(){const today=new Date().toDateString(),key='dice_'+today;if(localStorage.getItem(key)){showToast('حجر الحظ استخدمته اليوم 🎲');return}localStorage.setItem(key,'1');const n=1+Math.floor(Math.random()*6),gain=n*5;document.getElementById('diceMsg').textContent='🎲 النتيجة: '+n+' — ربحت '+gain+' XP';addXP(gain,'حجر الحظ')}
function loadProfileData(){const u=localStorage.getItem('bm7_username');if(u){let e=document.getElementById('miniUsername');if(e)e.textContent=u;let b=document.getElementById('boardMe');if(b)b.textContent=u}updateStatsUI()}
window.addEventListener('load',loadProfileData);
function togglePrivateProfile(){const key='bm7_private_profile';const now=localStorage.getItem(key)!=='1';localStorage.setItem(key,now?'1':'0');updatePrivacyUI();showToast(now?'تم تفعيل خصوصية ملفك 🔒':'تم جعل الملف عامًا')}
function updatePrivacyUI(){const e=document.getElementById('privacyStatus');if(e)e.textContent=localStorage.getItem('bm7_private_profile')==='1'?'خاص 🔒':'عام'}
window.addEventListener('load',updatePrivacyUI);
