/* ===== BM7 REAL ACTIVATION v8 =====
   Requires the accompanying bm7-activate.sql to be run once in Supabase SQL Editor.
*/
window.BM7Live={user:null,presenceChannel:null,chatChannel:null};
async function bm7LiveInit(){const sb=window.bm7Supabase;if(!sb)return;const {data:{session}}=await sb.auth.getSession();if(!session?.user)return;BM7Live.user=session.user;const {data:p}=await sb.from('profiles').select('username,display_name,bio').eq('id',session.user.id).maybeSingle();if(p){localStorage.setItem('bm7_username',p.username||'');['miniUsername','profileUsername'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=p.username?'@'+p.username:'@user'})}const uid=session.user.id;if(BM7Live.presenceChannel)await sb.removeChannel(BM7Live.presenceChannel);BM7Live.presenceChannel=sb.channel('bm7-presence',{config:{presence:{key:uid}}});BM7Live.presenceChannel.on('presence',{event:'sync'},()=>{}).subscribe(async status=>{if(status==='SUBSCRIBED')await BM7Live.presenceChannel.track({user_id:uid,username:p?.username||session.user.email?.split('@')[0]||'user',online:true,at:new Date().toISOString()})});updatePresenceUI()}
window.bm7LiveInit=bm7LiveInit;
async function bm7RealtimeChat(name='Batman',otherUserId=null){const sb=window.bm7Supabase;if(!sb||!BM7Live.user){openChatV6(name,true);return}if(!otherUserId){openChatV6(name,true);return}const me=BM7Live.user.id,room=[me,otherUserId].sort().join('_');const {data:rows}=await sb.from('messages').select('id,sender_id,body,created_at').eq('room_key',room).order('created_at',{ascending:true}).limit(100);const bubbles=(rows||[]).map(m=>`<div class="chat-bubble ${m.sender_id===me?'me':''}">${escapeHtmlV6(m.body)}</div>`).join('');openBM7Modal('💬 '+name,`<div class="chat-head"><div class="chat-user"><div class="chat-avatar">🦇</div><div><b>${name}</b><div class="presence"><span class="presence-dot online"></span> متصل</div></div></div></div><div class="call-actions"><button class="btn" onclick="startCall('${name}','voice')">📞 صوت</button><button class="btn" onclick="startCall('${name}','video')">📹 فيديو</button></div><div class="chat-messages" id="bm7ChatMessages">${bubbles}</div><div class="chat-compose"><input id="bm7ChatInput" placeholder="اكتب رسالة..." onkeydown="if(event.key==='Enter')sendRealtimeChat('${otherUserId}')"><button class="btn primary" onclick="sendRealtimeChat('${otherUserId}')">إرسال</button></div>`);if(BM7Live.chatChannel)await sb.removeChannel(BM7Live.chatChannel);BM7Live.chatChannel=sb.channel('bm7-chat-'+room).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`room_key=eq.${room}`},payload=>{const box=document.getElementById('bm7ChatMessages');if(!box)return;const m=payload.new;box.insertAdjacentHTML('beforeend',`<div class="chat-bubble ${m.sender_id===me?'me':''}">${escapeHtmlV6(m.body)}</div>`);box.scrollTop=box.scrollHeight}).subscribe()}
window.bm7RealtimeChat=bm7RealtimeChat;
window.sendRealtimeChat=async function(otherUserId){const sb=window.bm7Supabase,input=document.getElementById('bm7ChatInput');if(!sb||!BM7Live.user||!input||!input.value.trim())return;const me=BM7Live.user.id,body=input.value.trim(),room=[me,otherUserId].sort().join('_');const {error}=await sb.from('messages').insert({room_key:room,sender_id:me,receiver_id:otherUserId,body});if(error)toast('تعذر إرسال الرسالة: '+error.message);else input.value=''};
window.findBM7User=async function(username){const sb=window.bm7Supabase;if(!sb)return null;const {data}=await sb.from('profiles').select('id,username,display_name,bio').eq('username',username).maybeSingle();return data};
if(window.bm7Supabase)window.bm7Supabase.auth.onAuthStateChange((_event,session)=>{if(session?.user)setTimeout(bm7LiveInit,300)});
