/* ===== BM7 v11 — REAL WebRTC calling ===== */
window.BM7Call={pc:null,channel:null,signalChannel:null,callId:null,peerId:null,peerName:null,type:null,pending:null,localStream:null,remoteStream:null,connected:false};
function bm7CallEscape(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function bm7EnsureCallSignal(){const sb=window.bm7Supabase;if(!sb||!BM7Live.user)return;if(BM7Call.signalChannel)await sb.removeChannel(BM7Call.signalChannel);BM7Call.signalChannel=sb.channel('bm7-call-signal-'+BM7Live.user.id);BM7Call.signalChannel.on('broadcast',{event:'signal'},async payload=>{const m=payload.payload||{};if(!m||m.to!==BM7Live.user.id)return;await bm7HandleSignal(m)}).subscribe()}
async function bm7GetMedia(type){if(!navigator.mediaDevices?.getUserMedia)throw new Error('المتصفح لا يدعم المكالمات');return await navigator.mediaDevices.getUserMedia(type==='video'?{audio:true,video:{width:{ideal:720},height:{ideal:480}}}:{audio:true,video:false})}
function bm7CallUI(title,status,showVideo=false){return `<div class="bm7-call-screen"><div class="bm7-call-avatar">🦇</div><h3>${bm7CallEscape(title)}</h3><div id="bm7CallStatus" class="presence">${bm7CallEscape(status)}</div><video id="bm7RemoteVideo" class="bm7-call-video" autoplay playsinline></video><audio id="bm7RemoteAudio" autoplay></audio><div class="bm7-call-actions"><button class="btn" id="bm7MuteBtn" onclick="bm7ToggleMute()">🎙️ كتم</button>${showVideo?'<button class="btn" id="bm7CamBtn" onclick="bm7ToggleCamera()">📷 الكاميرا</button>':''}<button class="btn" onclick="bm7Hangup()">❌ إنهاء</button></div><div class="bm7-call-mini">يتم الاتصال مباشرة بين الجهازين عبر WebRTC.</div></div>`}
async function bm7BroadcastSignal(to,msg){const sb=window.bm7Supabase;if(!sb||!BM7Call.signalChannel)return;await BM7Call.signalChannel.send({type:'broadcast',event:'signal',payload:{...msg,to,from:BM7Live.user.id}})}
async function bm7CreatePeer(){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});BM7Call.pc=pc;BM7Call.remoteStream=new MediaStream();pc.onicecandidate=e=>{if(e.candidate)bm7BroadcastSignal(BM7Call.peerId,{kind:'ice',callId:BM7Call.callId,candidate:e.candidate})};pc.ontrack=e=>{e.streams[0]?.getTracks().forEach(t=>BM7Call.remoteStream.addTrack(t));const v=document.getElementById('bm7RemoteVideo'),a=document.getElementById('bm7RemoteAudio');if(BM7Call.type==='video'&&v){v.srcObject=BM7Call.remoteStream;v.style.display='block'}if(a)a.srcObject=BM7Call.remoteStream};pc.onconnectionstatechange=()=>{BM7Call.connected=pc.connectionState==='connected';const s=document.getElementById('bm7CallStatus');if(s)s.textContent=pc.connectionState==='connected'?'متصل الآن 🟢':pc.connectionState==='connecting'?'جاري الاتصال…':pc.connectionState;if(['failed','closed','disconnected'].includes(pc.connectionState)){if(pc.connectionState==='failed')bm7Hangup(false)}};return pc}
async function bm7StartRealCall(peerId,peerName,type){if(!BM7Live.user){toast('سجّل دخولك أولاً');return}if(peerId===BM7Live.user.id){toast('لا يمكنك الاتصال بنفسك');return}try{BM7Call={...BM7Call,peerId,peerName,type,callId:crypto.randomUUID(),connected:false};BM7Call.localStream=await bm7GetMedia(type);openBM7Modal(type==='video'?'📹 مكالمة فيديو':'📞 مكالمة صوتية',bm7CallUI(peerName,'جاري الاتصال…',type==='video'));const pc=await bm7CreatePeer();BM7Call.localStream.getTracks().forEach(t=>pc.addTrack(t,BM7Call.localStream));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await bm7BroadcastSignal(peerId,{kind:'offer',callId:BM7Call.callId,type,offer})}catch(e){toast('تعذر تشغيل الميكروفون/الكاميرا: '+e.message);bm7Hangup(false)}}
async function bm7IncomingCall(m){if(BM7Call.callId){await bm7BroadcastSignal(m.from,{kind:'busy',callId:m.callId});return}BM7Call.pending=m;openBM7Modal(m.type==='video'?'📹 مكالمة واردة':'📞 مكالمة واردة',`<div class="bm7-call-screen"><div class="bm7-call-avatar">🦇</div><h3>${bm7CallEscape(m.name||'مستخدم BM7')}</h3><div class="presence"><span class="presence-dot online"></span> يتصل بك الآن</div><div class="bm7-call-actions"><button class="btn primary" onclick="bm7AcceptCall()">✅ قبول</button><button class="btn" onclick="bm7RejectCall()">❌ رفض</button></div></div>`)}
async function bm7AcceptCall(){const m=BM7Call.pending;if(!m)return;closeBM7Modal();try{BM7Call={...BM7Call,peerId:m.from,peerName:m.name||'مستخدم BM7',type:m.type,callId:m.callId,connected:false,pending:null};BM7Call.localStream=await bm7GetMedia(m.type);openBM7Modal(m.type==='video'?'📹 مكالمة فيديو':'📞 مكالمة صوتية',bm7CallUI(BM7Call.peerName,'جاري الاتصال…',m.type==='video'));const pc=await bm7CreatePeer();BM7Call.localStream.getTracks().forEach(t=>pc.addTrack(t,BM7Call.localStream));await pc.setRemoteDescription(new RTCSessionDescription(m.offer));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await bm7BroadcastSignal(m.from,{kind:'answer',callId:m.callId,answer})}catch(e){toast('تعذر قبول المكالمة: '+e.message);bm7Hangup(false)}}
async function bm7RejectCall(){const m=BM7Call.pending;if(m)await bm7BroadcastSignal(m.from,{kind:'reject',callId:m.callId});BM7Call.pending=null;closeBM7Modal()}
async function bm7HandleSignal(m){if(m.kind==='offer'){await bm7IncomingCall(m);return}if(!BM7Call.callId||m.callId!==BM7Call.callId)return;if(m.kind==='answer'&&BM7Call.pc){await BM7Call.pc.setRemoteDescription(new RTCSessionDescription(m.answer))}else if(m.kind==='ice'&&BM7Call.pc){try{await BM7Call.pc.addIceCandidate(new RTCIceCandidate(m.candidate))}catch(e){}}else if(m.kind==='reject'){toast('تم رفض المكالمة');bm7Hangup(false)}else if(m.kind==='busy'){toast('المستخدم في مكالمة أخرى');bm7Hangup(false)}else if(m.kind==='hangup'){bm7Hangup(false)}}
window.bm7ToggleMute=function(){const t=BM7Call.localStream?.getAudioTracks()?.[0];if(!t)return;t.enabled=!t.enabled;const b=document.getElementById('bm7MuteBtn');if(b)b.textContent=t.enabled?'🎙️ كتم':'🔇 إلغاء الكتم'};
window.bm7ToggleCamera=function(){const t=BM7Call.localStream?.getVideoTracks()?.[0];if(!t)return;t.enabled=!t.enabled;const b=document.getElementById('bm7CamBtn');if(b)b.textContent=t.enabled?'📷 الكاميرا':'🚫 تشغيل الكاميرا'};
window.bm7Hangup=async function(send=true){if(send&&BM7Call.peerId&&BM7Call.callId)await bm7BroadcastSignal(BM7Call.peerId,{kind:'hangup',callId:BM7Call.callId});BM7Call.localStream?.getTracks().forEach(t=>t.stop());BM7Call.pc?.close();BM7Call={...BM7Call,pc:null,localStream:null,remoteStream:null,callId:null,peerId:null,peerName:null,type:null,pending:null,connected:false};try{closeBM7Modal()}catch(e){}};
window.startCall=function(name,type){const peerId=window.__bm7SelectedPeerId;if(peerId){bm7StartRealCall(peerId,name,type);return}openBM7Modal(type==='video'?'📹 مكالمة فيديو مع '+name:'📞 مكالمة صوتية مع '+name,`<div class="bm7-call-screen"><div class="bm7-call-avatar">🦇</div><h3>${bm7CallEscape(name)}</h3><div class="bm7-call-mini">افتح المحادثة مع المستخدم أولاً لبدء مكالمة حقيقية.</div><div class="bm7-call-actions"><button class="btn" onclick="closeBM7Modal()">إغلاق</button></div></div>`) };
window.bm7RealtimeChat=function(name,id){window.__bm7SelectedPeerId=id;if(typeof window.openBM7Chat==='function')window.openBM7Chat(name,id);else if(typeof openBM7Modal==='function')openBM7Modal('💬 '+name,`<div class="bm7-call-actions"><button class="btn primary" onclick="bm7StartRealCall('${id}','${bm7CallEscape(name)}','audio')">📞 صوت</button><button class="btn primary" onclick="bm7StartRealCall('${id}','${bm7CallEscape(name)}','video')">📹 فيديو</button></div>`) };
if(window.bm7Supabase){setTimeout(()=>bm7EnsureCallSignal(),900);window.bm7Supabase.auth.onAuthStateChange((_event,session)=>{if(session?.user){BM7Live.user=session.user;setTimeout(bm7EnsureCallSignal,300)}})}
